name: IdentityNow Campaign Runner

on:
  push:
    branches: [ master ]

jobs:
  run-campaign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get install -y podman

    - name: Build Campaign Runner Image
      run: |
        podman build -t campaign-runner .

    - name: Run campaign-runner
      run: |
        podman run --rm \
          -v ${{ github.workspace }}:/app:Z \
          -e client_id="${{ secrets.CLIENT_ID }}" \
          -e client_secret="${{ secrets.CLIENT_SECRET }}" \
          -e BASE_URL="${{ secrets.BASE_URL }}" \
          campaign-runner bash /app/run.sh
